### ISSUE TITLE
Deletes history of all existing parameters

### ISSUE THREAD

**Issue by Tony-Zheng-Zocdoc** [novemberdobby/autoProperties#1]
Looks like this currently hides all existing parameters from history tab. After running a build all i see is "no defined parameters" even with parameters defined.

edit: I'm using TC version 2017.1.4 (build 47070)

**Comment by ojintoad** [comment]
Recreated also on TC 2017.2.2

Critical TC functionality it's obscuring so it feels like a higher priority issue.

**Comment by novemberdobby** [comment]
Could you provide a screenshot or two?

This might require a change in how we set the parameters. Currently the server is not "aware" of the updated params, at least not in the way it is for customised builds.

I don't know if customised parameters can be set programatically when the build is triggered. Hmm.

**Comment by ojintoad** [comment]
It's hard to keep this installed on a shared instance given its impact so no from me on screenshot.

**Comment by novemberdobby** [comment]
Fixed, parameters are no longer hidden. This will restore them on old builds too.

I'm still going to investigate showing updated params in the "user defined" section though as it'd be nice to have.
